model:
  rho_cryst: 1400
  kv: 0.5233

pbe:
  scheme: 'first'
  spacing: 'geometric'
  no_class: 50
  q: 1
  L_0: 0.00001
  domain: [ 0, 1 ]  # will be set by geometric spacing automatically

initial:
  T0: 350
  T_j0: 350
  c0: 0.2259
  N_0: 1000000.0
  mu: 0.0001
  sigma: 0.00001
  scheme: 'linear'
  n_discr: 10