model:
  rho: 1000
  rho_cryst: 1400
  delta_H_cryst: 0
  c_p: 4.2
  U: 100
  A: 5.53
  V_j: 0.1
  rho_j: 1043
  c_p_j: 4.2
  kv: 0.5233
  V: 0.1
  N_0: 100000000.0  #1e10
  mu: 0.0001
  sigma: 0.00001
  no_stages: 2

pbe:
  scheme: 'WENO5'
  spacing: 'geometric'
  no_class: 200
  q: 4
  L_0: 0.000001  # 1e-6
  domain: [ 0, 1 ]  # will be set by geometric spacing automatically

initial:
  T0: 323.15
  T_j0: 323.15
  c0: 0.177